project_id = "kbmomlmiazkiceemprpz"

[functions.get-market-data]
verify_jwt = true

[functions.send-ammo-alert]
verify_jwt = true

[functions.admin-invite-user]
verify_jwt = true

[functions.admin-set-password]
verify_jwt = false

[functions.admin-forgot-password]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.admin-get-users]
verify_jwt = true

[functions.admin-update-role]
verify_jwt = true

[functions.admin-sync-owner]
verify_jwt = true
